version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: inventory_mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: inventory_backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/InventoryManagementSystem
      - JWT_SECRET=mysecretkey123
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
    restart: always

  frontend:
    build: ./frontend
    container_name: inventory_frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

volumes:
  mongodb_data:
